APP_ENV=local
APP_DEBUG=true
APP_KEY=Z1OR5f6NGNKD1616s8hY7tsu7iwB4ULL

DB_HOST=localhost
DB_DATABASE=theliteracycenter
DB_USERNAME=root
DB_PASSWORD=281292vv

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null